### ISSUE TITLE
structure value popup window location

### ISSUE THREAD

**Issue by mpieck** [luusluus/vscode-parquet-visualizer#44] opened 2024-10-05 17:15 UTC
When you click on a cell that is first to the left, the value popup window is located to the left of the first column, so its hidden under explorer tab and not visible at all. Moreover the popup window is pined to the first column on the left to the viewed cell, if it is the first column in the file the popup is as narrow as the first cell. The popup location should depend on the location of the cursor location in the app window.

![obraz](https://github.com/user-attachments/assets/0fffa8c3-ce27-4a45-b2b2-20eb49673951)

**Comment by luusluus** [comment] 2024-10-05 21:35
Thank you for the detailed description. Could you provide me the parquet file you tested this on?

**Comment by mpieck** [comment] 2024-10-06 14:32
Sure, file attached. I'm using 1.94.0 VSC and newest extension.

[train-00000-of-00001.zip](https://github.com/user-attachments/files/17269734/train-00000-of-00001.zip)

**Comment by luusluus** [comment] 2024-10-10 11:00
The problem was caused by inline HTML elements in your parquet data. Due to existing CSS Rules and this rendered HTML element from parquet file, it caused the popup to behave like this.

Normally the popup is positioned on where it is clicked.

I've added a function to escape HTML inside the popup.

**Comment by luusluus** [comment] 2024-10-12 03:41
fixed in https://github.com/luusluus/vscode-parquet-visualizer/pull/48/files#diff-d17a9ee3a2ad709fc632293632be1d74e61e7773957f4c847f5d00d279215a26R132

**Closed by luusluus** 2024-10-12 03:41 UTC
