### ISSUE TITLE
Bug: Data & Query Views - Sorting directly on column applies to only Current Page and not to whole dataset

### ISSUE THREAD

**Issue by darrylthom** [luusluus/vscode-parquet-visualizer#87] opened 2024-11-21 13:52 UTC
Clicking a column to sort it only applies to the data currently visually being shown on the page, but the expected behavior would most likely be to re-sort the **entire** dataset, which means rows from other pages may suddenly become visible.

**Comment by darrylthom** [comment] 2024-11-21 14:13
Search rows in page is also causing the same issue but I think that was the intended behavior. It might actually be more valuable though to have it search in all pages.

**Comment by luusluus** [comment] 2024-11-25 23:14
It was indeed the intended behavior. I can look into the search rows through all pages and sorting on the entire dataset. Should be possible

**Comment by luusluus** [comment] 2024-12-27 18:31
This should be fixed in the latest release

**Closed by luusluus** 2024-12-27 18:31 UTC

**Comment by darrylthom** [comment] 2024-12-27 19:12
Sorting seems to be working now but not the search. Search filter also needs to be applied again directly after running a new query.
